# Entry G16: Components Comparison

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('ggplot')
%matplotlib inline

import warnings
warnings.filterwarnings('once')

from neo4j import GraphDatabase

In [3]:
uri = "bolt://localhost:7687"

driver = GraphDatabase.driver(uri, auth=('neo4j', 'password'))

uni_session = driver.session(database="unimodal")
bi_session = driver.session(database="bimodal")
mix_session = driver.session(database="mixmodal")

//anaconda3/lib/python3.7/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

## Component count

In [11]:
uni_component = pd.DataFrame(uni_session.run('''CALL gds.wcc.stream({
  nodeProjection: 'Hero',
  relationshipProjection: {
  KNOWS: {
  type: 'KNOWS',
  orientation:'UNDIRECTED'
  }}
})
YIELD componentId
RETURN componentId as uni_id, count(*) as uni_size
Order by uni_size DESC''').data())

uni_component['uni_pct'] = round(uni_component['uni_size'] / uni_component['uni_size'].sum() *100, 2)

uni_component.head()

   uni_id  uni_size  uni_pct
0       0      6403    99.44
1     239         9     0.14
2      92         7     0.11
3    3504         2     0.03
4     465         1     0.02

In [9]:
bi_component = pd.DataFrame(bi_session.run('''CALL gds.wcc.stream({
  nodeProjection: ['*'],
  relationshipProjection: '*'})
YIELD componentId
RETURN componentId as bi_id, count(*) as bi_size
Order by bi_size DESC''').data())

bi_component['bi_pct'] = round(bi_component['bi_size'] / bi_component['bi_size'].sum() *100, 2)

bi_component.head()

   bi_id  bi_size  bi_pct
0      0    19029   99.68
1   2667       11    0.06
2    700        8    0.04
3  15007        4    0.02
4  14297        3    0.02

In [13]:
mix_component = pd.DataFrame(mix_session.run('''CALL gds.wcc.stream({
  nodeProjection: ['*'],
  relationshipProjection: '*'})
YIELD componentId
RETURN componentId as mix_id, count(*) as mix_size
Order by mix_size DESC''').data())

mix_component['component_pct'] = round(mix_component['mix_size'] / mix_component['mix_size'].sum() *100, 2)

mix_component.head()

   mix_id  mix_size  component_pct
0       0     19029          99.68
1    2667        11           0.06
2     700         8           0.04
3   15007         4           0.02
4   14297         3           0.02

In [14]:
print('Unimodal number of components:', len(uni_component))
print('Bimodal number of components:', len(bi_component))
print('Mixmodal number of components:', len(mix_component))

Unimodal number of components: 22
Bimodal number of components: 22
Mixmodal number of components: 22

//anaconda3/lib/python3.7/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [18]:
uni_component.merge(bi_component, left_index=True, right_index=True).merge(mix_component, left_index=True, right_index=True).columns

//anaconda3/lib/python3.7/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

Index(['uni_id', 'uni_size', 'uni_pct', 'bi_id', 'bi_size', 'bi_pct', 'mix_id',
       'mix_size', 'component_pct'],
      dtype='object')

In [20]:
uni_component.merge(bi_component, left_index=True, right_index=True).merge(
    mix_component, left_index=True, right_index=True)[['uni_id', 'bi_id', 'mix_id', 'uni_size', 'bi_size', 'mix_size',
                                                      'uni_pct', 'bi_pct', 'component_pct']]

,uni_id,bi_id,mix_id,uni_size,bi_size,mix_size,uni_pct,bi_pct,component_pct
0,0,0,0,6403,19029,19029,99.44,99.68,99.68
1,239,2667,2667,9,11,11,0.14,0.06,0.06
2,92,700,700,7,8,8,0.11,0.04,0.04
3,3504,15007,15007,2,4,4,0.03,0.02,0.02
4,465,14297,14297,1,3,3,0.02,0.02,0.02
5,576,17041,17041,1,3,3,0.02,0.02,0.02
6,832,4544,4544,1,2,2,0.02,0.01,0.01
7,1084,5744,5744,1,2,2,0.02,0.01,0.01
8,1381,7048,7048,1,2,2,0.02,0.01,0.01
9,1829,8580,8580,1,2,2,0.02,0.01,0.01
10,2105,9767,9767,1,2,2,0.02,0.01,0.01
11,2127,11289,11289,1,2,2,0.02,0.01,0.01
12,2759,11902,11902,1,2,2,0.02,0.01,0.01
13,3045,12020,12020,1,2,2,0.02,0.01,0.01
14,3284,13798,13798,1,2,2,0.02,0.01,0.01
15,3470,14647,14647,1,2,2,0.02,0.01,0.01
16,4505,14950,14950,1,2,2,0.02,0.01,0.01
17,4596,16460,16460,1,2,2,0.02,0.01,0.01
18,4772,16568,16568,1,2,2,0.02,0.01,0.01
19,4933,16836,16836,1,2,2,0.02,0.01,0.01
20,5016,17187,17187,1,2,2,0.02,0.01,0.01
21,6395,19035,19035,1,2,2,0.02,0.01,0.01